# Generated by Django 3.0.4 on 2020-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='summary',
            field=models.TextField(default='this is cool !'),
        ),
    ]
